# -*- coding: utf-8 -*-
"""2012-2024 연도,팀,연봉,WAR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19269gjXTCF_JB-cZbfLEvPD43UIEbR4N
"""

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

!pip install selenium

!pip install webdriver-manager

import requests

# 외부 API를 사용하여 현재 IP 정보 확인
response = requests.get("https://ipinfo.io/json")
data = response.json()

# IP 주소, 지역, 국가 출력
print(f"IP 주소: {data['ip']}")
print(f"위치: {data['city']}, {data['region']}, {data['country']}")

driver_path = 'chromedriver.exe'

!chromium-browser --version

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pandas as pd

chrome_driver_path = '/path/to/chromedriver'
# 2. 옵션 설정
options = Options()
options.add_argument("--headless")
options.add_argument("--disable-gpu")
options.add_argument("--no-sandbox")

# 3. Chrome WebDriver 실행
service = Service(chrome_driver_path)
driver = webdriver.Chrome(service=service, options=options)

# 4. URL 접속
url = "https://statiz.sporki.com/add/?m=salary&year=2013&ct_code="
driver.get(url)

# 5. 웹 페이지가 완전히 로딩될 때까지 기다리기 (최대 10초)
try:
    # section_warp 클래스가 있는 section 요소를 기다림
    WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.CLASS_NAME, "section_warp"))
    )
    print("웹 페이지가 로드되었습니다.")
except Exception as e:
    print(f"❗ 에러 발생: {e}")

# 6. 페이지 소스를 가져와 BeautifulSoup으로 파싱
soup = BeautifulSoup(driver.page_source, 'html.parser')

# 7. 'section_warp' 클래스 찾기
section = soup.find('section', class_='section_warp')

# 8. 테이블이 있는지 확인하고 데이터를 추출
data = []
if section:
    table = section.find('table')
    if table:
        rows = table.find_all('tr')
        for row in rows[1:]:  # 첫 번째 row는 헤더이므로 건너뛰기
            cols = row.find_all('td')
            texts = [col.get_text(strip=True) for col in cols]
            if len(texts) >= 5:
                data.append({
                    '선수명': texts[0],
                    '연도': texts[1],
                    '팀': texts[2],
                    '연봉': texts[3],
                    'WAR': texts[4]
                })

        # 9. 데이터프레임으로 변환
        df = pd.DataFrame(data)
        df['연봉'] = pd.to_numeric(df['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
        print(df.head())
    else:
        print("❗ 테이블을 찾을 수 없습니다.")
else:
    print("❗ section_warp을 찾을 수 없습니다.")

# 10. 브라우저 종료
driver.quit()

print(df)

df.isnull().sum()

#2012
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2012&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df1 = pd.DataFrame(data)
    df1['연봉'] = pd.to_numeric(df1['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df1.head())
else:
    print("x")

print(df1)

#2013
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2013&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='item_box')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df2 = pd.DataFrame(data)
    df2['연봉(만원)	'] = pd.to_numeric(df2['연봉(만원)	'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df2.head())
else:
    print("x")

ip_check = requests.get("https://httpbin.org/ip")
print(ip_check.text)

ip_check = requests.get("https://httpbin.org/ip")
print(ip_check.text)



print(df2)

#2014
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2014&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df3 = pd.DataFrame(data)
    df3['연봉'] = pd.to_numeric(df3['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df3.head())
else:
    print("x")

print(df3)

#2015
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2015&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df4 = pd.DataFrame(data)
    df4['연봉'] = pd.to_numeric(df4['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df4.head())
else:
    print("x")

print(df4)

#2016
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2016&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df5 = pd.DataFrame(data)
    df5['연봉'] = pd.to_numeric(df5['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df5.head())
else:
    print("x")

print(df5)

#2017
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2017&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df6 = pd.DataFrame(data)
    df6['연봉'] = pd.to_numeric(df6['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df6.head())
else:
    print("x")

print(df6)

#2018
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2018&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df7 = pd.DataFrame(data)
    df7['연봉'] = pd.to_numeric(df7['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df7.head())
else:
    print("x")

print(df7)

#2019
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2019&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df8 = pd.DataFrame(data)
    df8['연봉'] = pd.to_numeric(df8['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df8.head())
else:
    print("x")

print(df8)

#2020
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2020&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df9 = pd.DataFrame(data)
    df9['연봉'] = pd.to_numeric(df9['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df9.head())
else:
    print("x")

print(df9)

#2021
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2021&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df10 = pd.DataFrame(data)
    df10['연봉'] = pd.to_numeric(df10['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df10.head())
else:
    print("x")

print(df10)

#2022
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2022&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df11 = pd.DataFrame(data)
    df11['연봉'] = pd.to_numeric(df11['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df11.head())
else:
    print("x")

print(df11)

#2023
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2023&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df12 = pd.DataFrame(data)
    df12['연봉'] = pd.to_numeric(df12['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df12.head())
else:
    print("x")

print(df12)

#2024
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2024&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df13 = pd.DataFrame(data)
    df13['연봉'] = pd.to_numeric(df13['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df13.head())
else:
    print("x")

print(df13)

#2025
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/add/?m=salary&year=2025&ct_code="
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df14 = pd.DataFrame(data)
    df14['연봉'] = pd.to_numeric(df14['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df14.head())
else:
    print("x")

print(df14)

"""타격"""

#타격
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://statiz.sporki.com/stats/?m=main&m2=batting"
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

section = soup.find('section', class_='section_warp')
if section:
    table = section.find('table')
else:
  table = None

data = []

if table:
    rows = table.find_all('tr')
    for row in rows[1:]:
        cols = row.find_all('td')

        texts = []
        for c in cols:
            text = c.get_text(strip=True)
            texts.append(text)
        cols = texts

        if len(cols) >= 5:
            data.append({
                '선수명': cols[0],
                '연도': cols[1],
                '팀': cols[2],
                '연봉': cols[3],
                'WAR': cols[4]
            })

    df = pd.DataFrame(data)
    df['연봉'] = pd.to_numeric(df['연봉'].str.replace(",", "").str.replace("원", ""), errors='coerce')
    print(df.head())
else:
    print("x")