# -*- coding: utf-8 -*-
"""FA WAR 가설 검증_ver2_신은서

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QClCa7GvYaryqCajJXwfTz0UdoeK5ALh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind
from google.colab import files

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !apt-get -qq install -y fonts-nanum
# !fc-cache -fv
# !rm -rf ~/.cache/matplotlib

import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# 폰트 경로 + 이름 적용
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
fontprop = fm.FontProperties(fname=font_path)
plt.rcParams['font.family'] = fontprop.get_name()
plt.rcParams['axes.unicode_minus'] = False

# 폰트 확인
print("✅ 현재 폰트:", plt.rcParams['font.family'])

plt.figure(figsize=(4, 3))
plt.plot([1, 2, 3], [10, 30, 20])
plt.title("한글 테스트 성공!")
plt.xlabel("X축")
plt.ylabel("Y축")
plt.grid(True)
plt.show()